/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  merchantSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },

    // Standalone pages
    'faq',
    'changelog',
  ],
};

module.exports = sidebars;

